### ISSUE TITLE
Delegate

### ISSUE THREAD

**Issue by cousins217** [Marxon13/M13PDFKit#14]
Was just wondering if there is any sort of delegate that can be passed in to be notified of things such as page changes, etc.

Also, I saw there is a Swift branch, any time frame on that? My reason for asking is that I am more capable in Swift, so if I were to try and add this functionality myself, it'd probably be to that version!

Thanks for the awesome framework!

**Comment by simalexan** [comment]
@cousins217 its in progress, so hopefully it will be done soon, we didn't have much time during the past year, but will continue the development and possibly in a month or two finish the Swift branch (2.x version of Swift)
