### ISSUE TITLE
Swift issue

### ISSUE THREAD

**Issue by chlebta** [Marxon13/M13PDFKit#19]
Hello, 
I'm trying to use this library with swift but I get an error at this line 
>  var document: PDFKDocument = PDFKDocument(contentsOfFile: "http://www.adobe.com/devnet/acrobat/pdfs/pdf_open_parameters.pdf", password: nil)

the error text : 
> fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by dinuvld** [comment]
I also encounter the same error, @Marxon13, can you give us some insight on what is happening?

**Comment by DucVinhDang** [comment]
Hey chlebta, you should use NSBundle.mainBundle().pathForResource(...) to get the path of your file in your app instead of using a direct link.

**Comment by bofiaza** [comment]
@chlebta, put a question mark (?) or exclamation mark (!) after PDFKDocument:

var document: PDFKDocument? = PDFKDocument(contentsOfFile: "http://www.adobe.com/devnet/acrobat/pdfs/pdf_open_parameters.pdf", password: nil)

**Comment by simalexan** [comment]
Hey @chlebta, did it work out for you? 
The proper way would be to download the file first to the `.CachesDirectory` directory and then pass the downloaded file location to the `PDFKDocument` constructor.

If the issue occurs again, pls reopen it
