### ISSUE TITLE
Pod spec does not work

### ISSUE THREAD

**Issue by martinjo** [Marxon13/M13PDFKit#2]
Hi,

When adding M13PDFKit via cocoa pods, only the Resource-folder is downloaded.

**Comment by simalexan** [comment]
+1
I've already sent an almost same email myself to Brandon (Marxon13) two days ago, so I think he will be merging your PR soon enough.

**Comment by Marxon13** [comment]
Updated and pushed!

**Comment by simalexan** [comment]
Yep, got the source files from the pod now :+1:  good work!
