### ISSUE TITLE
About Share

### ISSUE THREAD

**Issue by engmohamedsalah** [Marxon13/M13PDFKit#20]
Is there any ability to share the book by Apps like (GMail , Whatsapp , ...)

**Comment by simalexan** [comment]
@engmohamedsalah Gmail has the capability for that, so on the Share view just tap "More" and enable "Gmail". Whatsapp doesn't seem to allow file sharing of a PDF file.

if you need any further assitance, write it in the comments

**Comment by engmohamedsalah** [comment]
what about others like Facebook , Bluetooth, ....
like any app allow share 
Airdrop for example can i enable it

**Comment by simalexan** [comment]
@engmohamedsalah if the application allows pdf file sharing, then you can.
If its not visible in the application list, just repeat the steps when sharing it ("More", and then enable it)
Airdrop is already possible. Try it out
