### ISSUE TITLE
POD problem

### ISSUE THREAD

**Issue by caglarergul** [Marxon13/M13PDFKit#22]
I get "linker command failed with exit code 1 (use -v to see invocation)" error and it is not building for running.

**Comment by caglarergul** [comment]
I solved it.

**Comment by simalexan** [comment]
@caglarergul great, what was the issue? 
Usually its a project file problem, so clearing and reinstalling the pods solves the issue.

**Comment by caglarergul** [comment]
I could not install pods into the project. That's my mistake :)

**Comment by simalexan** [comment]
@caglarergul not a problem :)
